import { useEffect, useMemo, useState } from 'react'
import { useSearchParams } from 'react-router-dom'
import { Printer, QrCode, Tags } from 'lucide-react'
import { PageHeader } from '@/components/ui/page-header'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Card, CardContent } from '@/components/ui/card'
import { Checkbox } from '@/components/ui/checkbox'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'
import { EmptyState } from '@/components/ui/empty-state'
import { LocationBadge } from '@/components/stock/LocationBadge'
import { useBins, useRows } from '@/hooks/useLocations'
import { useProductList } from '@/hooks/useProducts'
import { useDebouncedValue } from '@/hooks/useDebouncedValue'
import { useAppToast } from '@/hooks/useAppToast'
import { supabase, SUPABASE_URL } from '@/lib/supabase'
import { downloadBlob } from '@/lib/csv'
import { cn } from '@/lib/utils'

type Mode = 'bins' | 'products'

/**
 * Label sheets (App Flow §5.11). The PDF is generated by the `label-pdf` Edge
 * Function — QR of the location code for bins, Code 128 of the barcode for
 * products — because scanning needs labels that exist.
 */
export default function Labels() {
  const [params] = useSearchParams()
  const [mode, setMode] = useState<Mode>(params.get('products') ? 'products' : 'bins')
  const [rowId, setRowId] = useState<string>('all')
  const [selected, setSelected] = useState<Set<string>>(new Set())
  const [search, setSearch] = useState('')
  const [busy, setBusy] = useState(false)
  const debounced = useDebouncedValue(search, 250)

  const { data: rows = [] } = useRows()
  const { data: bins = [] } = useBins(rowId === 'all' ? undefined : rowId)
  const { data: productPage } = useProductList({ search: debounced, pageSize: 50, status: 'active' })
  const { showError, showSuccess } = useAppToast()


  // Deep links from a product or bin page pre-select that one item.
  useEffect(() => {
    const productId = params.get('products')
    const binId = params.get('bins')
    const row = params.get('row')
    if (productId) {
      setMode('products')
      setSelected(new Set([productId]))
    } else if (binId) {
      setMode('bins')
      setSelected(new Set([binId]))
    } else if (row) {
      setMode('bins')
      setRowId(row)
    }
  }, [params])

  const items = useMemo(() => {
    if (mode === 'bins') {
      return bins.map((b) => ({ id: b.id, primary: b.location_code, secondary: b.code }))
    }
    return (productPage?.rows ?? []).map((p) => ({
      id: p.product_id,
      primary: p.sku,
      secondary: p.name,
    }))
  }, [bins, mode, productPage])

  const toggle = (id: string) =>
    setSelected((prev) => {
      const next = new Set(prev)
      if (next.has(id)) next.delete(id)
      else next.add(id)
      return next
    })

  const generate = async () => {
    if (selected.size === 0) return
    setBusy(true)
    try {
      const { data: session } = await supabase.auth.getSession()
      const token = session.session?.access_token
      if (!token) throw new Error('UNAUTHENTICATED:sign in again')

      // The function streams a PDF, so this goes through fetch rather than
      // supabase.functions.invoke (which expects JSON back).
      const response = await fetch(`${SUPABASE_URL}/functions/v1/label-pdf`, {
        method: 'POST',
        headers: {
          Authorization: `Bearer ${token}`,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ type: mode, ids: [...selected] }),
      })

      if (!response.ok) {
        const body = await response.json().catch(() => null)
        throw new Error(
          body?.error ? `${body.error.code}:${body.error.message}` : `LABEL_FAILED:${response.status}`,
        )
      }

      downloadBlob(`bintrack-${mode}-labels.pdf`, await response.blob())
      showSuccess(`${selected.size} labels generated`, 'A4 sheets, 3 × 8 per page.')
    } catch (error) {
      showError(error, 'Could not generate the labels')
    } finally {
      setBusy(false)
    }
  }

  return (
    <>
      <PageHeader
        title="Labels"
        description="Bin QR codes and product barcodes, ready to print."
        actions={
          <Button
            disabled={selected.size === 0}
            loading={busy}
            onClick={() => void generate()}
          >
            <Printer />
            Generate PDF ({selected.size})
          </Button>
        }
      />

      <div className="mb-4 flex flex-wrap gap-2">
        <div className="flex gap-2">
          <Button
            variant={mode === 'bins' ? 'primary' : 'secondary'}
            onClick={() => {
              setMode('bins')
              setSelected(new Set())
            }}
          >
            <QrCode />
            Bin QR labels
          </Button>
          <Button
            variant={mode === 'products' ? 'primary' : 'secondary'}
            onClick={() => {
              setMode('products')
              setSelected(new Set())
            }}
          >
            <Tags />
            Product barcodes
          </Button>
        </div>

        {mode === 'bins' ? (
          <Select
            value={rowId}
            onValueChange={(v) => {
              setRowId(v)
              setSelected(new Set())
            }}
          >
            <SelectTrigger className="w-56">
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="all">All rows</SelectItem>
              {rows.map((row) => (
                <SelectItem key={row.id} value={row.id}>
                  {row.warehouse.code}-{row.code}
                  {row.name ? ` · ${row.name}` : ''}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
        ) : (
          <Input
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            placeholder="Filter products by SKU or name…"
            className="w-64"
            aria-label="Filter products"
          />
        )}

        <Button
          variant="ghost"
          onClick={() =>
            setSelected((prev) =>
              prev.size === items.length ? new Set() : new Set(items.map((i) => i.id)),
            )
          }
          disabled={items.length === 0}
        >
          {selected.size === items.length && items.length > 0 ? 'Clear selection' : 'Select all'}
        </Button>
      </div>

      {items.length === 0 ? (
        <EmptyState
          icon={mode === 'bins' ? QrCode : Tags}
          title={mode === 'bins' ? 'No bins in this row' : 'No products match'}
          description={
            mode === 'bins'
              ? 'Create bins under Locations first.'
              : 'Try a different search term.'
          }
        />
      ) : (
        <Card>
          <CardContent className="grid gap-2 p-3 sm:grid-cols-2 lg:grid-cols-3">
            {items.map((item) => {
              const checked = selected.has(item.id)
              return (
                <label
                  key={item.id}
                  className={cn(
                    'flex cursor-pointer items-center gap-3 rounded-md border p-2.5',
                    checked ? 'border-foreground bg-accent' : 'border-border hover:bg-accent',
                  )}
                >
                  <Checkbox checked={checked} onCheckedChange={() => toggle(item.id)} />
                  <span className="min-w-0">
                    {mode === 'bins' ? (
                      <LocationBadge code={item.primary} />
                    ) : (
                      <span className="block font-mono text-small">{item.primary}</span>
                    )}
                    <span className="block truncate text-small text-muted-foreground">
                      {item.secondary}
                    </span>
                  </span>
                </label>
              )
            })}
          </CardContent>
        </Card>
      )}

      <p className="mt-4 text-small text-muted-foreground">
        Bin labels are 40 × 40 mm QR codes carrying the location code; product labels are Code 128
        of the barcode, falling back to the SKU. Both print 24 to an A4 sheet.
      </p>
    </>
  )
}
